// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 02 Nov 2024 01:06:14 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "opus.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

