// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 02 Nov 2024 01:06:14 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package opus

/*
#cgo pkg-config: opus
#include "opus.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *Encoder) Ref() *C.OpusEncoder {
	if x == nil {
		return nil
	}
	return (*C.OpusEncoder)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Encoder) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewEncoderRef converts the C object reference into a raw struct reference without wrapping.
func NewEncoderRef(ref unsafe.Pointer) *Encoder {
	return (*Encoder)(ref)
}

// NewEncoder allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewEncoder() *Encoder {
	return (*Encoder)(allocEncoderMemory(1))
}

// allocEncoderMemory allocates memory for type C.OpusEncoder in C.
// The caller is responsible for freeing the this memory via C.free.
func allocEncoderMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfEncoderValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfEncoderValue = unsafe.Sizeof([1]C.OpusEncoder{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Encoder) PassRef() *C.OpusEncoder {
	if x == nil {
		x = (*Encoder)(allocEncoderMemory(1))
	}
	return (*C.OpusEncoder)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *Decoder) Ref() *C.OpusDecoder {
	if x == nil {
		return nil
	}
	return (*C.OpusDecoder)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Decoder) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewDecoderRef converts the C object reference into a raw struct reference without wrapping.
func NewDecoderRef(ref unsafe.Pointer) *Decoder {
	return (*Decoder)(ref)
}

// NewDecoder allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewDecoder() *Decoder {
	return (*Decoder)(allocDecoderMemory(1))
}

// allocDecoderMemory allocates memory for type C.OpusDecoder in C.
// The caller is responsible for freeing the this memory via C.free.
func allocDecoderMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfDecoderValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfDecoderValue = unsafe.Sizeof([1]C.OpusDecoder{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Decoder) PassRef() *C.OpusDecoder {
	if x == nil {
		x = (*Decoder)(allocDecoderMemory(1))
	}
	return (*C.OpusDecoder)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *Repacketizer) Ref() *C.OpusRepacketizer {
	if x == nil {
		return nil
	}
	return (*C.OpusRepacketizer)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Repacketizer) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewRepacketizerRef converts the C object reference into a raw struct reference without wrapping.
func NewRepacketizerRef(ref unsafe.Pointer) *Repacketizer {
	return (*Repacketizer)(ref)
}

// NewRepacketizer allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewRepacketizer() *Repacketizer {
	return (*Repacketizer)(allocRepacketizerMemory(1))
}

// allocRepacketizerMemory allocates memory for type C.OpusRepacketizer in C.
// The caller is responsible for freeing the this memory via C.free.
func allocRepacketizerMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfRepacketizerValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfRepacketizerValue = unsafe.Sizeof([1]C.OpusRepacketizer{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Repacketizer) PassRef() *C.OpusRepacketizer {
	if x == nil {
		x = (*Repacketizer)(allocRepacketizerMemory(1))
	}
	return (*C.OpusRepacketizer)(unsafe.Pointer(x))
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// copyPInt16Bytes copies the data from Go slice as *C.opus_int16.
func copyPInt16Bytes(slice *sliceHeader) (*C.opus_int16, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfInt16Value) * slice.Len,
		Cap:  int(sizeOfInt16Value) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.opus_int16)(mem0), allocs
}

// allocInt16Memory allocates memory for type C.opus_int16 in C.
// The caller is responsible for freeing the this memory via C.free.
func allocInt16Memory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfInt16Value))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfInt16Value = unsafe.Sizeof([1]C.opus_int16{})

// copyPUcharBytes copies the data from Go slice as *C.uchar.
func copyPUcharBytes(slice *sliceHeader) (*C.uchar, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfUcharValue) * slice.Len,
		Cap:  int(sizeOfUcharValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.uchar)(mem0), allocs
}

// allocUcharMemory allocates memory for type C.uchar in C.
// The caller is responsible for freeing the this memory via C.free.
func allocUcharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfUcharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfUcharValue = unsafe.Sizeof([1]C.uchar{})

// copyPFloatBytes copies the data from Go slice as *C.float.
func copyPFloatBytes(slice *sliceHeader) (*C.float, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfFloatValue) * slice.Len,
		Cap:  int(sizeOfFloatValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.float)(mem0), allocs
}

// allocFloatMemory allocates memory for type C.float in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFloatMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFloatValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFloatValue = unsafe.Sizeof([1]C.float{})
