// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 26 Sep 2016 16:20:36 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package opus

/*
#cgo pkg-config: opus
#include "opus/opus.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Int as defined in opus/opus_types.h:151
	Int = 0
	// Ok as defined in opus/opus_defines.h:46
	Ok = 0
	// BadArg as defined in opus/opus_defines.h:48
	BadArg = -1
	// BufferTooSmall as defined in opus/opus_defines.h:50
	BufferTooSmall = -2
	// InternalError as defined in opus/opus_defines.h:52
	InternalError = -3
	// InvalidPacket as defined in opus/opus_defines.h:54
	InvalidPacket = -4
	// Unimplemented as defined in opus/opus_defines.h:56
	Unimplemented = -5
	// InvalidState as defined in opus/opus_defines.h:58
	InvalidState = -6
	// AllocFail as defined in opus/opus_defines.h:60
	AllocFail = -7
	// Restrict as defined in opus/opus_defines.h:98
	Restrict = 0
	// Inline as defined in opus/opus_defines.h:110
	Inline = 0
	// SetApplicationRequest as defined in opus/opus_defines.h:130
	SetApplicationRequest = 4000
	// GetApplicationRequest as defined in opus/opus_defines.h:131
	GetApplicationRequest = 4001
	// SetBitrateRequest as defined in opus/opus_defines.h:132
	SetBitrateRequest = 4002
	// GetBitrateRequest as defined in opus/opus_defines.h:133
	GetBitrateRequest = 4003
	// SetMaxBandwidthRequest as defined in opus/opus_defines.h:134
	SetMaxBandwidthRequest = 4004
	// GetMaxBandwidthRequest as defined in opus/opus_defines.h:135
	GetMaxBandwidthRequest = 4005
	// SetVbrRequest as defined in opus/opus_defines.h:136
	SetVbrRequest = 4006
	// GetVbrRequest as defined in opus/opus_defines.h:137
	GetVbrRequest = 4007
	// SetBandwidthRequest as defined in opus/opus_defines.h:138
	SetBandwidthRequest = 4008
	// GetBandwidthRequest as defined in opus/opus_defines.h:139
	GetBandwidthRequest = 4009
	// SetComplexityRequest as defined in opus/opus_defines.h:140
	SetComplexityRequest = 4010
	// GetComplexityRequest as defined in opus/opus_defines.h:141
	GetComplexityRequest = 4011
	// SetInbandFecRequest as defined in opus/opus_defines.h:142
	SetInbandFecRequest = 4012
	// GetInbandFecRequest as defined in opus/opus_defines.h:143
	GetInbandFecRequest = 4013
	// SetPacketLossPercRequest as defined in opus/opus_defines.h:144
	SetPacketLossPercRequest = 4014
	// GetPacketLossPercRequest as defined in opus/opus_defines.h:145
	GetPacketLossPercRequest = 4015
	// SetDtxRequest as defined in opus/opus_defines.h:146
	SetDtxRequest = 4016
	// GetDtxRequest as defined in opus/opus_defines.h:147
	GetDtxRequest = 4017
	// SetVbrConstraintRequest as defined in opus/opus_defines.h:148
	SetVbrConstraintRequest = 4020
	// GetVbrConstraintRequest as defined in opus/opus_defines.h:149
	GetVbrConstraintRequest = 4021
	// SetForceChannelsRequest as defined in opus/opus_defines.h:150
	SetForceChannelsRequest = 4022
	// GetForceChannelsRequest as defined in opus/opus_defines.h:151
	GetForceChannelsRequest = 4023
	// SetSignalRequest as defined in opus/opus_defines.h:152
	SetSignalRequest = 4024
	// GetSignalRequest as defined in opus/opus_defines.h:153
	GetSignalRequest = 4025
	// GetLookaheadRequest as defined in opus/opus_defines.h:154
	GetLookaheadRequest = 4027
	// GetSampleRateRequest as defined in opus/opus_defines.h:156
	GetSampleRateRequest = 4029
	// GetFinalRangeRequest as defined in opus/opus_defines.h:157
	GetFinalRangeRequest = 4031
	// GetPitchRequest as defined in opus/opus_defines.h:158
	GetPitchRequest = 4033
	// SetGainRequest as defined in opus/opus_defines.h:159
	SetGainRequest = 4034
	// GetGainRequest as defined in opus/opus_defines.h:160
	GetGainRequest = 4045
	// SetLsbDepthRequest as defined in opus/opus_defines.h:161
	SetLsbDepthRequest = 4036
	// GetLsbDepthRequest as defined in opus/opus_defines.h:162
	GetLsbDepthRequest = 4037
	// GetLastPacketDurationRequest as defined in opus/opus_defines.h:163
	GetLastPacketDurationRequest = 4039
	// SetExpertFrameDurationRequest as defined in opus/opus_defines.h:164
	SetExpertFrameDurationRequest = 4040
	// GetExpertFrameDurationRequest as defined in opus/opus_defines.h:165
	GetExpertFrameDurationRequest = 4041
	// SetPredictionDisabledRequest as defined in opus/opus_defines.h:166
	SetPredictionDisabledRequest = 4042
	// GetPredictionDisabledRequest as defined in opus/opus_defines.h:167
	GetPredictionDisabledRequest = 4043
	// Auto as defined in opus/opus_defines.h:183
	Auto = -1000
	// BitrateMax as defined in opus/opus_defines.h:184
	BitrateMax = -1
	// ApplicationVoip as defined in opus/opus_defines.h:188
	ApplicationVoip = 2048
	// ApplicationAudio as defined in opus/opus_defines.h:191
	ApplicationAudio = 2049
	// ApplicationRestrictedLowdelay as defined in opus/opus_defines.h:194
	ApplicationRestrictedLowdelay = 2051
	// SignalVoice as defined in opus/opus_defines.h:196
	SignalVoice = 3001
	// SignalMusic as defined in opus/opus_defines.h:197
	SignalMusic = 3002
	// BandwidthNarrowband as defined in opus/opus_defines.h:198
	BandwidthNarrowband = 1101
	// BandwidthMediumband as defined in opus/opus_defines.h:199
	BandwidthMediumband = 1102
	// BandwidthWideband as defined in opus/opus_defines.h:200
	BandwidthWideband = 1103
	// BandwidthSuperwideband as defined in opus/opus_defines.h:201
	BandwidthSuperwideband = 1104
	// BandwidthFullband as defined in opus/opus_defines.h:202
	BandwidthFullband = 1105
	// FramesizeArg as defined in opus/opus_defines.h:204
	FramesizeArg = 5000
	// Framesize25Ms as defined in opus/opus_defines.h:205
	Framesize25Ms = 5001
	// Framesize5Ms as defined in opus/opus_defines.h:206
	Framesize5Ms = 5002
	// Framesize10Ms as defined in opus/opus_defines.h:207
	Framesize10Ms = 5003
	// Framesize20Ms as defined in opus/opus_defines.h:208
	Framesize20Ms = 5004
	// Framesize40Ms as defined in opus/opus_defines.h:209
	Framesize40Ms = 5005
	// Framesize60Ms as defined in opus/opus_defines.h:210
	Framesize60Ms = 5006
	// ResetState as defined in opus/opus_defines.h:640
	ResetState = 4028
)
