// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 26 Sep 2016 16:20:36 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package opus provides Go bindings for Opus implementation by the Xiph.Org Foundation
*/
package opus
