// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 02 Nov 2024 01:06:14 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package opus provides Go bindings for Opus implementation by the Xiph.Org Foundation
*/
package opus
