// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 26 Sep 2016 16:20:36 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package opus

/*
#cgo pkg-config: opus
#include "opus/opus.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// EncoderGetSize function as declared in opus/opus.h:171
func EncoderGetSize(channels int32) int32 {
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	__ret := C.opus_encoder_get_size(cchannels)
	__v := (int32)(__ret)
	return __v
}

// EncoderCreate function as declared in opus/opus.h:208
func EncoderCreate(fs int32, channels int32, application int32, error *int32) *Encoder {
	cfs, _ := (C.opus_int32)(fs), cgoAllocsUnknown
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	capplication, _ := (C.int)(application), cgoAllocsUnknown
	cerror, _ := (*C.int)(unsafe.Pointer(error)), cgoAllocsUnknown
	__ret := C.opus_encoder_create(cfs, cchannels, capplication, cerror)
	__v := *(**Encoder)(unsafe.Pointer(&__ret))
	return __v
}

// EncoderInit function as declared in opus/opus.h:228
func EncoderInit(st *Encoder, fs int32, channels int32, application int32) int32 {
	cst, _ := (*C.OpusEncoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	cfs, _ := (C.opus_int32)(fs), cgoAllocsUnknown
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	capplication, _ := (C.int)(application), cgoAllocsUnknown
	__ret := C.opus_encoder_init(cst, cfs, cchannels, capplication)
	__v := (int32)(__ret)
	return __v
}

// Encode function as declared in opus/opus.h:263
func Encode(st *Encoder, pcm []int16, frameSize int32, data []byte, maxDataBytes int32) int32 {
	cst, _ := (*C.OpusEncoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	cpcm, _ := (*C.opus_int16)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&pcm)).Data)), cgoAllocsUnknown
	cframeSize, _ := (C.int)(frameSize), cgoAllocsUnknown
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	cmaxDataBytes, _ := (C.opus_int32)(maxDataBytes), cgoAllocsUnknown
	__ret := C.opus_encode(cst, cpcm, cframeSize, cdata, cmaxDataBytes)
	__v := (int32)(__ret)
	return __v
}

// EncodeFloat function as declared in opus/opus.h:304
func EncodeFloat(st *Encoder, pcm []float32, frameSize int32, data []byte, maxDataBytes int32) int32 {
	cst, _ := (*C.OpusEncoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	cpcm, _ := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&pcm)).Data)), cgoAllocsUnknown
	cframeSize, _ := (C.int)(frameSize), cgoAllocsUnknown
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	cmaxDataBytes, _ := (C.opus_int32)(maxDataBytes), cgoAllocsUnknown
	__ret := C.opus_encode_float(cst, cpcm, cframeSize, cdata, cmaxDataBytes)
	__v := (int32)(__ret)
	return __v
}

// EncoderDestroy function as declared in opus/opus.h:315
func EncoderDestroy(st *Encoder) {
	cst, _ := (*C.OpusEncoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	C.opus_encoder_destroy(cst)
}

// DecoderGetSize function as declared in opus/opus.h:406
func DecoderGetSize(channels int32) int32 {
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	__ret := C.opus_decoder_get_size(cchannels)
	__v := (int32)(__ret)
	return __v
}

// DecoderCreate function as declared in opus/opus.h:423
func DecoderCreate(fs int32, channels int32, error *int32) *Decoder {
	cfs, _ := (C.opus_int32)(fs), cgoAllocsUnknown
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	cerror, _ := (*C.int)(unsafe.Pointer(error)), cgoAllocsUnknown
	__ret := C.opus_decoder_create(cfs, cchannels, cerror)
	__v := *(**Decoder)(unsafe.Pointer(&__ret))
	return __v
}

// DecoderInit function as declared in opus/opus.h:440
func DecoderInit(st *Decoder, fs int32, channels int32) int32 {
	cst, _ := (*C.OpusDecoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	cfs, _ := (C.opus_int32)(fs), cgoAllocsUnknown
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	__ret := C.opus_decoder_init(cst, cfs, cchannels)
	__v := (int32)(__ret)
	return __v
}

// Decode function as declared in opus/opus.h:462
func Decode(st *Decoder, data string, len int32, pcm []int16, frameSize int32, decodeFec int32) int32 {
	cst, _ := (*C.OpusDecoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	cdata, _ := unpackPUcharString(data)
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	cpcm, _ := (*C.opus_int16)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&pcm)).Data)), cgoAllocsUnknown
	cframeSize, _ := (C.int)(frameSize), cgoAllocsUnknown
	cdecodeFec, _ := (C.int)(decodeFec), cgoAllocsUnknown
	__ret := C.opus_decode(cst, cdata, clen, cpcm, cframeSize, cdecodeFec)
	__v := (int32)(__ret)
	return __v
}

// DecodeFloat function as declared in opus/opus.h:487
func DecodeFloat(st *Decoder, data string, len int32, pcm []float32, frameSize int32, decodeFec int32) int32 {
	cst, _ := (*C.OpusDecoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	cdata, _ := unpackPUcharString(data)
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	cpcm, _ := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&pcm)).Data)), cgoAllocsUnknown
	cframeSize, _ := (C.int)(frameSize), cgoAllocsUnknown
	cdecodeFec, _ := (C.int)(decodeFec), cgoAllocsUnknown
	__ret := C.opus_decode_float(cst, cdata, clen, cpcm, cframeSize, cdecodeFec)
	__v := (int32)(__ret)
	return __v
}

// DecoderDestroy function as declared in opus/opus.h:512
func DecoderDestroy(st *Decoder) {
	cst, _ := (*C.OpusDecoder)(unsafe.Pointer(st)), cgoAllocsUnknown
	C.opus_decoder_destroy(cst)
}

// PacketGetBandwidth function as declared in opus/opus.h:545
func PacketGetBandwidth(data string) int32 {
	cdata, _ := unpackPUcharString(data)
	__ret := C.opus_packet_get_bandwidth(cdata)
	__v := (int32)(__ret)
	return __v
}

// PacketGetSamplesPerFrame function as declared in opus/opus.h:556
func PacketGetSamplesPerFrame(data string, fs int32) int32 {
	cdata, _ := unpackPUcharString(data)
	cfs, _ := (C.opus_int32)(fs), cgoAllocsUnknown
	__ret := C.opus_packet_get_samples_per_frame(cdata, cfs)
	__v := (int32)(__ret)
	return __v
}

// PacketGetNbChannels function as declared in opus/opus.h:563
func PacketGetNbChannels(data string) int32 {
	cdata, _ := unpackPUcharString(data)
	__ret := C.opus_packet_get_nb_channels(cdata)
	__v := (int32)(__ret)
	return __v
}

// PacketGetNbFrames function as declared in opus/opus.h:572
func PacketGetNbFrames(packet string, len int32) int32 {
	cpacket, _ := unpackPUcharString(packet)
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	__ret := C.opus_packet_get_nb_frames(cpacket, clen)
	__v := (int32)(__ret)
	return __v
}

// PacketGetNbSamples function as declared in opus/opus.h:584
func PacketGetNbSamples(packet string, len int32, fs int32) int32 {
	cpacket, _ := unpackPUcharString(packet)
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	cfs, _ := (C.opus_int32)(fs), cgoAllocsUnknown
	__ret := C.opus_packet_get_nb_samples(cpacket, clen, cfs)
	__v := (int32)(__ret)
	return __v
}

// DecoderGetNbSamples function as declared in opus/opus.h:594
func DecoderGetNbSamples(dec *Decoder, packet string, len int32) int32 {
	cdec, _ := (*C.OpusDecoder)(unsafe.Pointer(dec)), cgoAllocsUnknown
	cpacket, _ := unpackPUcharString(packet)
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	__ret := C.opus_decoder_get_nb_samples(cdec, cpacket, clen)
	__v := (int32)(__ret)
	return __v
}

// PcmSoftClip function as declared in opus/opus.h:606
func PcmSoftClip(pcm []float32, frameSize int32, channels int32, softclipMem []float32) {
	cpcm, _ := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&pcm)).Data)), cgoAllocsUnknown
	cframeSize, _ := (C.int)(frameSize), cgoAllocsUnknown
	cchannels, _ := (C.int)(channels), cgoAllocsUnknown
	csoftclipMem, _ := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&softclipMem)).Data)), cgoAllocsUnknown
	C.opus_pcm_soft_clip(cpcm, cframeSize, cchannels, csoftclipMem)
}

// RepacketizerGetSize function as declared in opus/opus.h:756
func RepacketizerGetSize() int32 {
	__ret := C.opus_repacketizer_get_size()
	__v := (int32)(__ret)
	return __v
}

// RepacketizerInit function as declared in opus/opus.h:775
func RepacketizerInit(rp *Repacketizer) *Repacketizer {
	crp, _ := (*C.OpusRepacketizer)(unsafe.Pointer(rp)), cgoAllocsUnknown
	__ret := C.opus_repacketizer_init(crp)
	__v := *(**Repacketizer)(unsafe.Pointer(&__ret))
	return __v
}

// RepacketizerCreate function as declared in opus/opus.h:780
func RepacketizerCreate() *Repacketizer {
	__ret := C.opus_repacketizer_create()
	__v := *(**Repacketizer)(unsafe.Pointer(&__ret))
	return __v
}

// RepacketizerDestroy function as declared in opus/opus.h:786
func RepacketizerDestroy(rp *Repacketizer) {
	crp, _ := (*C.OpusRepacketizer)(unsafe.Pointer(rp)), cgoAllocsUnknown
	C.opus_repacketizer_destroy(crp)
}

// RepacketizerCat function as declared in opus/opus.h:835
func RepacketizerCat(rp *Repacketizer, data string, len int32) int32 {
	crp, _ := (*C.OpusRepacketizer)(unsafe.Pointer(rp)), cgoAllocsUnknown
	cdata, _ := unpackPUcharString(data)
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	__ret := C.opus_repacketizer_cat(crp, cdata, clen)
	__v := (int32)(__ret)
	return __v
}

// RepacketizerOutRange function as declared in opus/opus.h:869
func RepacketizerOutRange(rp *Repacketizer, begin int32, end int32, data []byte, maxlen int32) int32 {
	crp, _ := (*C.OpusRepacketizer)(unsafe.Pointer(rp)), cgoAllocsUnknown
	cbegin, _ := (C.int)(begin), cgoAllocsUnknown
	cend, _ := (C.int)(end), cgoAllocsUnknown
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	cmaxlen, _ := (C.opus_int32)(maxlen), cgoAllocsUnknown
	__ret := C.opus_repacketizer_out_range(crp, cbegin, cend, cdata, cmaxlen)
	__v := (int32)(__ret)
	return __v
}

// RepacketizerGetNbFrames function as declared in opus/opus.h:881
func RepacketizerGetNbFrames(rp *Repacketizer) int32 {
	crp, _ := (*C.OpusRepacketizer)(unsafe.Pointer(rp)), cgoAllocsUnknown
	__ret := C.opus_repacketizer_get_nb_frames(crp)
	__v := (int32)(__ret)
	return __v
}

// RepacketizerOut function as declared in opus/opus.h:912
func RepacketizerOut(rp *Repacketizer, data []byte, maxlen int32) int32 {
	crp, _ := (*C.OpusRepacketizer)(unsafe.Pointer(rp)), cgoAllocsUnknown
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	cmaxlen, _ := (C.opus_int32)(maxlen), cgoAllocsUnknown
	__ret := C.opus_repacketizer_out(crp, cdata, cmaxlen)
	__v := (int32)(__ret)
	return __v
}

// PacketPad function as declared in opus/opus.h:926
func PacketPad(data []byte, len int32, newLen int32) int32 {
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	cnewLen, _ := (C.opus_int32)(newLen), cgoAllocsUnknown
	__ret := C.opus_packet_pad(cdata, clen, cnewLen)
	__v := (int32)(__ret)
	return __v
}

// PacketUnpad function as declared in opus/opus.h:939
func PacketUnpad(data []byte, len int32) int32 {
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	__ret := C.opus_packet_unpad(cdata, clen)
	__v := (int32)(__ret)
	return __v
}

// MultistreamPacketPad function as declared in opus/opus.h:955
func MultistreamPacketPad(data []byte, len int32, newLen int32, nbStreams int32) int32 {
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	cnewLen, _ := (C.opus_int32)(newLen), cgoAllocsUnknown
	cnbStreams, _ := (C.int)(nbStreams), cgoAllocsUnknown
	__ret := C.opus_multistream_packet_pad(cdata, clen, cnewLen, cnbStreams)
	__v := (int32)(__ret)
	return __v
}

// MultistreamPacketUnpad function as declared in opus/opus.h:970
func MultistreamPacketUnpad(data []byte, len int32, nbStreams int32) int32 {
	cdata, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	clen, _ := (C.opus_int32)(len), cgoAllocsUnknown
	cnbStreams, _ := (C.int)(nbStreams), cgoAllocsUnknown
	__ret := C.opus_multistream_packet_unpad(cdata, clen, cnbStreams)
	__v := (int32)(__ret)
	return __v
}

// Strerror function as declared in opus/opus_defines.h:713
func Strerror(error int32) string {
	cerror, _ := (C.int)(error), cgoAllocsUnknown
	__ret := C.opus_strerror(cerror)
	__v := packPCharString(__ret)
	return __v
}

// GetVersionString function as declared in opus/opus_defines.h:719
func GetVersionString() string {
	__ret := C.opus_get_version_string()
	__v := packPCharString(__ret)
	return __v
}
