// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 26 Sep 2016 16:20:36 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package opus

/*
#cgo pkg-config: opus
#include "opus/opus.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Encoder as declared in opus/opus.h:164
type Encoder C.OpusEncoder

// Decoder as declared in opus/opus.h:399
type Decoder C.OpusDecoder

// Repacketizer as declared in opus/opus.h:751
type Repacketizer C.OpusRepacketizer

// Int16 type as declared in opus/opus_types.h:40
type Int16 int16

// Uint16 type as declared in opus/opus_types.h:41
type Uint16 uint16

// Int32 type as declared in opus/opus_types.h:42
type Int32 int32

// Uint32 type as declared in opus/opus_types.h:43
type Uint32 uint32
